version: '3.9'
services:
  db:
    container_name: mysql
    build:
      dockerfile: docker/database/Dockerfile
      context: .
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - app-net

  backend:
    container_name: ideaMixer-backend
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./
        target: /app
    command: python ./backend/main.py
    networks:
      - app-net

  vue:
    build:
      dockerfile: docker/frontend/Dockerfile
      context: .
    image: vue_img
    container_name: vue_container
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - "8080:8080"

volumes:
  db_data:

networks:
  app-net:
    driver: bridge