version: '3'
services:
  backend:
    container_name: ideaMixer-backend
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./
        target: /app
    command: python ./backend/main.py
  vue:
    build:
      dockerfile: docker/frontend/Dockerfile
      context: .
    image: vue_img
    container_name: vue_container
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - "8080:8080"